image: Ubuntu
configuration: Release
pull_requests:
  do_not_increment_build_number: true

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'

build:
  project: ./src/CmdR.csproj
  publish_nuget: true

deploy:
  provider: NuGet
  server: https://api.nuget.org/v3/index.json
  api_key:
    secure: LSDgU4mPwAAgPEwFB2CzDeBH7TzW4gGSAkCHHP69jZL7Udb2f6l2D0qLJNzjbGPI